[metadata]
creation_date = "2023/06/11"

[rule]
author = ["Mounir Hedna"]
description = "Test Update"
from = "now-6m"
name = "Test Update"
risk_score = 100
severity = "low"
type = "query"
rule_id = "00000000-0000-0000-0000-000000000100"
query = '''
event.dataset : zeek.http and user_agent.original: *Nmap* or user_agent.original: *Nikto*
'''

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"

[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"